### ISSUE TITLE
Different notes in sequencer vs pattern view

### ISSUE THREAD

**Issue by HerrFornit** [wasteddesign/ReBuzz#10]
compare Note G in channel 3 to horizontal seq picture.
<img width="343" alt="Screenshot seq horz" src="https://github.com/user-attachments/assets/a596bac2-63c9-4b1d-b5db-fe8cf503511f">
<img width="926" alt="Screenshot pattern" src="https://github.com/user-attachments/assets/85a92b0d-0bce-4eb6-a344-7a3756ef71e9">

**Comment by HerrFornit** [comment]
persists in v1769, perhaps cloese with piano roll  :) 👍

**Comment by wasteddesign** [comment]
In the Modern Sequence Editor settings, change the PatternBoxEventHint to Note.

**Comment by HerrFornit** [comment]
ok, I see. No bug. Thanx
