### ISSUE TITLE
do 'Snap Machines' in machine view results in overlayed machines

### ISSUE THREAD

**Issue by HerrFornit** [wasteddesign/ReBuzz#22]
v1769

ok, now I got it, the machines are after snap overlayed so it mimiks a loss and rewiring of machines, sorry for that.
On the other hand the grid does not work proper, because the machins are overlayed and not well sorted side by side.

**Comment by wasteddesign** [comment]
You can try to change the snap resolution from Machine View settings.

**Comment by HerrFornit** [comment]
ah ok, helps. No bug. Thanx.
'Set grid to' would make snapping perhaps unneccessary.
